### PR TITLE
Fix Examples to support configuration with no authentication

### LINKED ISSUE #15: Examples panic without BasicAuth
In transmission configurations without `BasicAuth` enabled, the examples throw `Error: NotPresent`. However, since configurations without `BasicAuth` are supported by transmission-rpc, it may be best to check whether the `TUSER` and `TPASS` environment variables are set, and assuming no authentication if they are not.

### PR DESCRIPTION
**Pull request by nickzana**
Fixes #15.

### CODE REVIEW

**Comment by red-avtovo** [comment]
Hey @nickzana!
Thx for the contribution. I would be honest that I didn't put that much effort to cover all the cases in examples. But the updated example indeed covers them

File: src/lib.rs [hunk 1]
```diff
@@ -380,11 +380,12 @@ mod tests {
         dotenv().ok();
         env_logger::init();
         let url = env::var("TURL")?;
-        let basic_auth = BasicAuth {
-            user: env::var("TUSER")?,
-            password: env::var("TPWD")?,
-        };
-        let client = TransClient::with_auth(&url, basic_auth);
+        let client;
+        if let (Ok(user), Ok(password)) = (env::var("TUSER"), env::var("TPWD")) {
```
Comment (red-avtovo) [inline src/lib.rs:384]: 👍 That is really nice

**Review by red-avtovo — APPROVED** [review]

**Comment by nickzana** [comment]
No problem! I appreciate your work regardless. I need it for a project that I'm working on, and my transmission configuration doesn't use BasicAuth, so I thought I would improve the examples to support that.
